// <auto-generated />
using System;
using GranjaAvicola.App.Persistent;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GranjaAvicola.App.Persistence.Migrations
{
    [DbContext(typeof(WebAppContext))]
    partial class WebAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GranjaAvicola.App.Domain.Diagnostico", b =>
                {
                    b.Property<int>("Id_Diagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiagnosticoVet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Registro")
                        .HasColumnType("int");

                    b.Property<int>("ID_Sugerencia")
                        .HasColumnType("int");

                    b.Property<int>("ID_VeterinarioCargo")
                        .HasColumnType("int");

                    b.Property<string>("Sugerencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Diagnostico");

                    b.ToTable("Diagnostico");
                });

            modelBuilder.Entity("GranjaAvicola.App.Domain.Galpon", b =>
                {
                    b.Property<int>("ID_Galpon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("Georeferencia")
                        .HasColumnType("int");

                    b.Property<int>("ID_OperarioCargo")
                        .HasColumnType("int");

                    b.Property<int>("ID_VeterinarioCargo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroAnimales")
                        .HasColumnType("int");

                    b.HasKey("ID_Galpon");

                    b.ToTable("Galpon");
                });

            modelBuilder.Entity("GranjaAvicola.App.Domain.Georeferencias", b =>
                {
                    b.Property<int>("Id_Georeferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("altitud")
                        .HasColumnType("float");

                    b.Property<double>("latitud")
                        .HasColumnType("float");

                    b.HasKey("Id_Georeferencia");

                    b.ToTable("Georeferencias");
                });

            modelBuilder.Entity("GranjaAvicola.App.Domain.Persona", b =>
                {
                    b.Property<int>("Id_Persona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<int>("ID_Rol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("Id_Persona");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("GranjaAvicola.App.Domain.Registro", b =>
                {
                    b.Property<int>("Id_Registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Agua")
                        .HasColumnType("float");

                    b.Property<double>("Alimento")
                        .HasColumnType("float");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("GallinasEnfermas")
                        .HasColumnType("int");

                    b.Property<int>("ID_Galpon")
                        .HasColumnType("int");

                    b.Property<int>("ID_Trabajador")
                        .HasColumnType("int");

                    b.Property<int>("PromedioHuevos")
                        .HasColumnType("int");

                    b.Property<double>("Temperatura")
                        .HasColumnType("float");

                    b.HasKey("Id_Registro");

                    b.ToTable("Registro");
                });

            modelBuilder.Entity("GranjaAvicola.App.Domain.Rol", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Rol");

                    b.ToTable("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
